# cloudbuild.yaml — Despliegue del backend API (NestJS) a Cloud Run

substitutions:
  # ---------------------------------------------------------------------------
  # 🔧 Servicio e imagen
  # ---------------------------------------------------------------------------
  _SERVICE_NAME: "portal-api"
  _REGION: "europe-west1"
  _REPO_NAME: "portal"
  _IMAGE_NAME: "api"
  _RUNTIME_SA: "portal-api@${PROJECT_ID}.iam.gserviceaccount.com"

  # ---------------------------------------------------------------------------
  # 🌍 Entorno de ejecución
  # ---------------------------------------------------------------------------
  _NODE_ENV: "production"
  _LOG_LEVEL: "info"

  # 🔐 JWT
  _JWT_ACCESS_SECRET: "changeme-access"
  _JWT_REFRESH_SECRET: "changeme-refresh"
  _JWT_ACCESS_EXPIRES: "15m"
  _JWT_REFRESH_EXPIRES: "7d"

  # 🧠 Mongo + OAuth (ajusta con tus valores reales o usa Secret Manager)
  _MONGO_URI: "mongodb+srv://USER:PASS@CLUSTER/portal?retryWrites=true&w=majority"

  _OAUTH_GOOGLE_CLIENT_ID: "<GOOGLE_CLIENT_ID>"
  _OAUTH_GOOGLE_CLIENT_SECRET: "<GOOGLE_CLIENT_SECRET>"
  _OAUTH_GOOGLE_REDIRECT_URI: "https://portal-api-<region>-<project>.a.run.app/auth/oauth/google/callback"

  _OAUTH_GITHUB_CLIENT_ID: "<GITHUB_CLIENT_ID>"
  _OAUTH_GITHUB_CLIENT_SECRET: "<GITHUB_CLIENT_SECRET>"
  _OAUTH_GITHUB_REDIRECT_URI: "https://portal-api-<region>-<project>.a.run.app/auth/oauth/github/callback"

  # 🔗 Orígenes del frontend (CORS) y URL del cliente
  _CORS_ORIGIN: "https://portal-frontend-<region>-<project>.a.run.app"
  _CLIENT_URL: "https://portal-frontend-<region>-<project>.a.run.app"

  _GCS_BUCKET: "bucket-name"
  _RESEND_API_KEY: "re_...."

steps:
  # 🧱 Build de la imagen
  - id: "build"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f","Dockerfile",
        "-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA",
        "-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest",
        "."
      ]

  # 📤 Push de ambas etiquetas (sha + latest)
  - id: "push-sha"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA"]
    waitFor: ["build"]

  - id: "push-latest"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest"]
    waitFor: ["build"]

  # 🚀 Despliegue en Cloud Run
  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      [
        "run","deploy","${_SERVICE_NAME}",
        "--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA",
        "--region","${_REGION}",
        "--platform","managed",
        "--allow-unauthenticated",
        "--service-account","${_RUNTIME_SA}",
        "--max-instances","1",
        "--cpu","1",
        "--memory","512Mi",
        "--timeout","300",
        "--update-env-vars",
        "NODE_ENV=${_NODE_ENV},LOG_LEVEL=${_LOG_LEVEL},MONGO_URI=${_MONGO_URI},CORS_ORIGIN=${_CORS_ORIGIN},CLIENT_URL=${_CLIENT_URL},JWT_ACCESS_SECRET=${_JWT_ACCESS_SECRET},JWT_REFRESH_SECRET=${_JWT_REFRESH_SECRET},JWT_ACCESS_EXPIRES=${_JWT_ACCESS_EXPIRES},JWT_REFRESH_EXPIRES=${_JWT_REFRESH_EXPIRES},OAUTH_GOOGLE_CLIENT_ID=${_OAUTH_GOOGLE_CLIENT_ID},OAUTH_GOOGLE_CLIENT_SECRET=${_OAUTH_GOOGLE_CLIENT_SECRET},OAUTH_GOOGLE_REDIRECT_URI=${_OAUTH_GOOGLE_REDIRECT_URI},OAUTH_GITHUB_CLIENT_ID=${_OAUTH_GITHUB_CLIENT_ID},OAUTH_GITHUB_CLIENT_SECRET=${_OAUTH_GITHUB_CLIENT_SECRET},OAUTH_GITHUB_REDIRECT_URI=${_OAUTH_GITHUB_REDIRECT_URI},GCS_BUCKET=${_GCS_BUCKET},RESEND_API_KEY=${_RESEND_API_KEY}"
      ]
    waitFor: ["push-sha","push-latest"]

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:latest"
